Iter15
KraDM09/shortener pull request #15
Opened 2024-07-31 19:34 UTC by KraDM09

отсроченное удаление url

2024-08-19 09:15 UTC, Bazys requested changes
очень рекомендую перевести хэндлеры в методы структуры

2024-08-19 09:15 UTC, Bazys commented on cmd/shortener/main.go
> +		pool, err := pgxpool.New(context.Background(), config.FlagDatabaseDsn)
контекст нам нужен, чтобы при остановке приложения, аккуратно все разрывать.
передавай контекст из main и только там можно порождать context.Background()

2024-08-19 09:15 UTC, Bazys commented on internal/app/handlers/get_url_by_hash.go
> +func GetURLByHashHandler(
вот прям просится структура, в которой одно из полей - storage.Storage
и не надо будет каждый раз в функцию передавать
и на интерфейсах потом можно будет сделать

2024-08-26 08:27 UTC, nburunova requested changes

2024-08-26 08:27 UTC, nburunova commented on cmd/shortener/main.go
> +		pool, err := pgxpool.New(context.Background(), config.FlagDatabaseDsn)
замечание не исправлено, создавать context.Background() рекомендуется отлько в main функции, откуда его передавать первым аргументом в остальные функции, в том числе в и getStorage первым аргументом

2024-08-26 08:27 UTC, nburunova commented on internal/app/access/cookie.go
> +				Expires: time.Now().Add(24 * 7 * time.Hour),
нужно еще ограничить время жизни токена в GenerateJWT?

2024-08-26 08:27 UTC, nburunova commented on internal/app/access/cookie.go
> +			if r.Method != http.MethodPost {
если не POST запрос, то куки не создаем?

2024-08-26 08:27 UTC, nburunova commented on internal/app/access/cookie.go
> +			panic(fmt.Errorf("ошибка при получении токена из куки %w", err))
надо ли нам паниковать и останавливать весь сервер при ошибке в одном запросе? Оправдана ли тут паника?

2024-08-26 08:27 UTC, nburunova commented on internal/app/access/cookie.go
> +		if userID == "" {
если куки есть, но имя пользователя пустое, то просто продолжим обработку запроса?

2024-08-26 08:27 UTC, nburunova commented on internal/app/access/cookie.go
> +package access
здесь нет возврата кода ответа 401, в задании было так: Если кука не содержит ID пользователя, хендлер должен возвращать HTTP-статус 401 Unauthorized.

2024-08-26 08:27 UTC, nburunova commented on internal/app/handlers/save_new_url.go
>  		rw.WriteHeader(http.StatusConflict)
тут наверное нужно return сделать, иначе выполнения кода продолжится с 43 строки

2024-08-26 08:27 UTC, nburunova commented on internal/app/storage/slice.go
>  var hashes []Link
к hash возможен конкуретный доступ? Может прикрыть мьютексом этот слайс?

2024-08-26 08:27 UTC, nburunova commented on internal/app/storage/slice.go
> +		link := s.Find(&hashes, hash.Short)
почему нельзя испоьзовать метод (s SliceStorage) Get(hash string) (*URL, error) а нужно было добавить новый Find?

2024-08-26 08:27 UTC, nburunova commented on internal/app/storage/slice.go
> +func (s SliceStorage) Get(hash string) (*URL, error) {
возможно hash стоит сделать map с ключом hash, а не слайс, тогда поиск по hash будет быстрее

2024-08-26 08:27 UTC, nburunova commented on internal/app/storage/pg.go
> +	ctx  context.Context
сохранять ctx в поле структуры - плохая практика https://pkg.go.dev/context Do not store Contexts inside a struct type; instead, pass a Context explicitly to each function that needs it. The Context should be the first parameter, typically named ctx.
Ctx должен передаваться первым параметрам в методах PG

2024-08-26 08:27 UTC, nburunova commented on internal/app/storage/pg.go
> +		ctx:  ctx,
используем входящий ctx в pgxpool.New(ctx, config.FlagDatabaseDsn) , но НЕ сохраняем его в структуру!

2024-08-26 08:27 UTC, nburunova commented on internal/app/storage/pg.go
> +func (pg PG) Save(hash string, url string, userID string) (string, error) {
первым параметом должен быть ctx context.Context

2024-08-26 08:27 UTC, nburunova commented on internal/app/storage/pg.go
>  	)
тут надо rows.Close()? в методе Get(hash string) Close есть, а тут нет.

2024-08-26 08:27 UTC, nburunova commented on internal/app/storage/pg.go
> +	return &records[0], nil
тут возвращается только первый элемент, а судя по коду выше, может быть несколько records. Предлагаю оптимизировать запрос в БД, если нам нужен только один элекмент, то делать запрос с LIMIT 1 например.

2024-08-26 08:27 UTC, nburunova commented on internal/app/handlers/user/delete_urls.go
> +	shortUrls := make([]string, 0, len(urls))
зачем нам создавать тут еще один слайс shortUrls? нельзя использовать urls?

2024-08-27 11:23 UTC, KraDM09 commented on internal/app/storage/pg.go
>  	)
он тут есть
https://github.com/KraDM09/shortener/blob/89bfe41d2a8304930079fba4058879d1dce5d038/internal/app/storage/pg.go#L89

2024-08-28 17:54 UTC, KraDM09 commented on internal/app/handlers/save_new_url.go
>  		rw.WriteHeader(http.StatusConflict)
видимо нет, у меня упал тест после правки
надо чтобы был 409 код и отдавалась короткая ссылка, которая уже в бд

2024-08-28 18:17 UTC, KraDM09 commented on internal/app/storage/slice.go
> +func (s SliceStorage) Get(hash string) (*URL, error) {
но у меня же есть уже [map](https://github.com/KraDM09/shortener/blob/89bfe41d2a8304930079fba4058879d1dce5d038/internal/app/storage/map.go#L3), пожалуй оставлю как есть

2024-08-29 04:59 UTC, KraDM09 commented on internal/app/access/cookie.go
> +			if r.Method != http.MethodPost {
Да, вот [логи](https://github.com/KraDM09/shortener/actions/runs/10608824059/job/29403520665?pr=15) из теста, который сломался

при GET запросе
expected: 401
actual  : 204

получается без токена ожидаем, что будет 401, а не генерируем куку и получаем 204 No Content

2024-08-29 05:04 UTC, KraDM09 commented on internal/app/access/cookie.go
> +		if userID == "" {
получается, что так
раз мы не генерим куку на GET запросы
значит выкинуть 401 мы должны в ручке

2024-08-29 05:06 UTC, KraDM09 commented on internal/app/access/cookie.go
> +package access
в ручке отвечаем 401
https://github.com/KraDM09/shortener/blob/iter15/internal/app/handlers/user/urls.go#L21

2024-08-30 13:08 UTC, nburunova requested changes

2024-08-30 13:08 UTC, nburunova commented on internal/app/access/cookie.go
> +package access
тут произошло размазывание ответственности за авторизацию между миддлваре и хендлреами, сейчас решение об 401 формируется в хендлере, а не в миддлваре, которое ответственно за access. 
Давай всю логику по 401 перенесем сюда?
Пусть мидлваре отправляет 401 в ответ и не передает реквест дальше, если возникла ситуация неавторизованного пользователя.
Или пропускает запрос дальше, когда это валидно, например когда это GET.
Хендлеры не должны обладать знаниями о логике авторизации

2024-08-30 13:08 UTC, nburunova commented on internal/app/storage/slice.go
> +	defer mu.Unlock()
можно использовать sync.RWMutex , для операций чтения взводить RWLock()

2024-08-30 13:08 UTC, nburunova commented on internal/app/storage/map.go
> +	mapHashes  = make(map[string]string)
тут тоже получается нужен лок для защиты мап, так как несколько клиентов могут одновременно вызывать действия над мапами типа Save\ Get и тд используй sync.RWLock

2024-08-30 13:08 UTC, nburunova commented on internal/app/storage/slice.go
> +func (s SliceStorage) Get(hash string) (*URL, error) {
для чего нужены отдельные  slice storage и map storage?

2024-08-31 07:30 UTC, KraDM09 commented
Ответ [на](https://github.com/KraDM09/shortener/pull/15#discussion_r1738630834)
Нужны были мне для лучшего понимания Dependency Injection

2024-09-02 13:47 UTC, nburunova approved these changes

2024-09-14 10:43 UTC, merged